### ISSUE TITLE
[Features request]List directory and files

### ISSUE THREAD

**Issue by Cyraus** [piotrmurach/tty-file#10]
I want the user to choose a directory, but it's too complicated to implement with 
`tty-prompt`. Can you provide a function to list and select a directory?
Recommend optional parameters: `list directory only`.

**Comment by piotrmurach** [comment]
The scope for this library is file & directory operations to make it easy to create, copy, change contents but not format, display content. To list directory and its files see [tty-tree](https://github.com/piotrmurach/tty-tree).

**Comment by Cyraus** [comment]
@piotrmurach Maybe I didn’t express it clearly. **I want the user to choose a directory,** just like `testdisk`, the `tty-tree` can't do this.

**Comment by piotrmurach** [comment]
@Cyraus You expressed your desire clearly enough the first time around. I was trying to be helpful and tell you about all the `tty-*` libs that when combined, can potentially help solve your problem. The best place for such a feature would be `tty-prompt`. Do you have time to implement and submit PR?

**Comment by Cyraus** [comment]
@piotrmurach Sorry for the late reply.
I don't have this need anymore, thanks!
