### ISSUE TITLE
TTY::File.binary? fails if the file contains a UTF8 character at byte 4096

### ISSUE THREAD

**Issue by Fjan** [piotrmurach/tty-file#11]
### Describe the problem
TTY::File.binary? reads only the first 4096 bytes of a file to detect if it's binary. If a UTF8 text file happens to contain a character at the boundary of bytes 4096 and 4097 then it gets split and the file is no longer a valid text file and thus gets marked as binary.

### Steps to reproduce the problem
Get the example text file [here](https://gist.github.com/Fjan/9eb5a47fe9d5eac835558320929bb121)
```
TTY::File.binary?('reproduce_tty_bug.txt')
```

### Actual behaviour
true

### Expected behaviour
false

### Describe your environment

* OS version: MacOS 10.14.6
* Ruby version: 2.6.3
* TTY::File version: 0.7.1

As an aside, I also noticed a small bug on line 367 of that same file: `file_a` in the error message should be `file_b`

**Comment by piotrmurach** [comment]
Hi Jan,

Thank you for this great report! It really helped to fix the issue.

Now, after the file block size is exceeded the file is read up until a valid character is found.

Released `v0.8.0` which hopefully will fix the issue for you.
