### ISSUE TITLE
chmod doesn't seem to accept "+x"

### ISSUE THREAD

**Issue by rzane** [piotrmurach/tty-file#12]
### Are you in the right place?

I hope so!

### Describe the problem

`TTY::File.chmod` doesn't respect `+x`.

### Steps to reproduce the problem

```ruby
irb(main):024:0> sprintf "%04o", (File.stat('foo.txt').mode & 07777)
=> "0644"
irb(main):025:0> TTY::File.chmod 'foo.txt', '+x', verbose: false
=> ["foo.txt"]
irb(main):026:0> sprintf "%04o", (File.stat('foo.txt').mode & 07777)
=> "0644"
```

### Actual behaviour

Nothing happens. The permission don't change.

### Expected behaviour

I expected `TTY::File.chmod` to behave similarly to `FileUtils`:

```ruby
irb(main):024:0> sprintf "%04o", (File.stat('foo.txt').mode & 07777)
=> "0644"
irb(main):027:0> FileUtils.chmod '+x', 'foo.txt'
=> ["foo.txt"]
irb(main):028:0> sprintf "%04o", (File.stat('foo.txt').mode & 07777)
=> "0755"
```

### Describe your environment

* OS version: macOS
* Ruby version: 2.5.3
* TTY::File version: 0.8.0

**Comment by piotrmurach** [comment]
Hi Ray,

Thanks for using `tty-file` and reporting this issue!

Currently, the permission string expects who will be affected by the change and the type of change. For example, `u+x` or `g+x` should work fine. The bare `+x` won't work. Happy to accept a patch to allow this behaviour as well.

**Comment by rzane** [comment]
I could change `[ugoa]` to `[ugoa]?` and prepend `"a"` when `setting =~ /^[+-]/`. But, I don't fully understand why the permissions string needs to be parsed [here](https://github.com/piotrmurach/tty-file/blob/c42653d3915b2913856e36502b6a1af9339ce922/lib/tty/file.rb#L142-L153)?

From what I can tell, it seems like `FileUtils` supports all of the expected use cases. All of the tests still pass when I change the method definition to this:

```ruby
def chmod(relative_path, permissions, **options)
  log_status(:chmod, relative_path, options.fetch(:verbose, true),
                                    options.fetch(:color, :green))
  ::FileUtils.chmod_R(permissions, relative_path) unless options[:noop]
end
```

**Comment by piotrmurach** [comment]
If that's the case then it makes sense to remove it. I'll first update the gem to work with Ruby `2.7` and then refactor this bit. I'm racking my brains and cannot remember why I thought this was necessary unless this functionality has been added in more recent versions of Ruby. This gem is built to work with Ruby `2.0` and above.
