### ISSUE TITLE
TTY::File output brakes TTY::Spinner

### ISSUE THREAD

**Issue by i5okie** [piotrmurach/tty-file#6]
Working on a Gem.
Just found this behaviour:

Gem versions:
**tty-file** ~> 0.6.0
**tty-spinner** ~> 0.8.0

_Example code:_
```ruby
spinner.auto_run
TTY::File.create_dir(tree, path)
spinner.success
```
_Example output:_
```
#  ⠙ creating directories
#      create  app
#      create  app/Gemfile
#  ✔ creating directories
```

I've tried wrapping TTY::File block inside spinner.run block. But then I don't have access to my instance methods/variables.

Workaround is to turn verbose output off.
Just wish verbose output could somehow be nicely integrated with spinner.
Though I'm not sure how I'd even implement that.

**Comment by piotrmurach** [comment]
Hi Ivan,

Thanks for using the tty gems!

Let's forget about `tty-file` for a second and simplify your example to:

```ruby
spinner.auto_run
puts '    create   app'
puts '    create   app/Gemfile'
spinner.success
```
which outputs:
```ruby
#  ⠙ creating directories
#      create  app
#      create  app/Gemfile
#  ✔ creating directories
```

Does that mean that `puts` breaks `TTY::Spinner`? The `tty-spinner` prints characters to screen and anything that produces a newline character will cause terminal cursor to move down by one row.

Further, let's imagine a scenario where 50 directories/files are created. Would you expect the spinner to 'know' to go up 50 terminal lines up and mark `creating directories` with a checkmark and then bring the cursor back down to original place or scroll up the terminal screen up. It sounds strange to say the least? I'm not sure that would be a great user experience.

The `tty-spinner` is meant for indeterminate tasks that by themeselves don't output anything and hence you need to provide user with some feedback like a loading indication. In your case `tty-file` produces output to terminal to notify of what is being done and hence the spinner seems a very unnecessary addition.

**Comment by i5okie** [comment]
Yeah, I've thought about this since. Silly.

**Comment by piotrmurach** [comment]
One solution would be to add some logging capabilities to `tty-spinner` that would display any output 'above' the spinner. However, I've never had a need for this hence it doesn't exist in the core library.

Quite often if you wish to notify people of different things that happen during spinning action, you can use the [update](https://github.com/piotrmurach/tty-spinner#26-update) call. In your case you would need to hook into the output from `tty-file` using the `:output` option and pass some stream that you would read from and pass each new line to `update` call. However, this also seems like overkill solution.
