### ISSUE TITLE
Some file manipulation methods accept Pathname instances, and some don't

### ISSUE THREAD

**Issue by yarmiganosca** [piotrmurach/tty-file#7]
### Steps to reproduce the problem
```
TTY::File.create_file(Pathname.pwd/'a.txt')
```
I know this example doesn't actually need a Pathname instance because of how relative paths work, but there are cases were it is much easier to provide TTY::File methods Pathname instances instead of Strings that indicate relative_paths, and I was surprised when that didn't work in these cases. Moreover, some methods (TTY::File.safe_append_to_file, for instance) that do work when passed Pathname instances.

### Actual behaviour
It results in a NoMethodError because Pathname doesn't define gsub.

### Expected behaviour
I expected Pathname instances to be accepted in place of file path String instances across the documented TTY::File methods.

### Describe your environment
* OS version: Ubuntu 16.04
* Ruby version: 2.5.1
* TTY::File version: 0.7.0

### Other notes
I'm more than happy to write the PR for this (making all documented methods that take String paths also take Pathname instances), I'd just like some indication whether it'd be welcome or not.

**Comment by piotrmurach** [comment]
Hi Chris,

Thanks for using tty-file gem!

Agreed! By all means do submit PRs with tests and I will happily review and merge.
